### ISSUE TITLE
Problem with Kernel 5.x?

### ISSUE THREAD

**Issue by aviatorhh** [craigpeacock/mcp251x.c#4]
I get the following

```
make -C /lib/modules/5.10.103-v7+/build M=/usr/local/src/mcp251x modules
make[1]: Entering directory '/usr/src/linux-headers-5.10.103-v7+'
  CC [M]  /usr/local/src/mcp251x/mcp251x.o
/usr/local/src/mcp251x/mcp251x.c:60:10: fatal error: linux/can/platform/mcp251x.h: No such file or directory
   60 | #include <linux/can/platform/mcp251x.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [scripts/Makefile.build:280: /usr/local/src/mcp251x/mcp251x.o] Error 1
make[1]: *** [Makefile:1825: /usr/local/src/mcp251x] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.10.103-v7+'
make: *** [Makefile:4: all] Error 2
```
I have on my system
```
/usr/src/linux-headers-5.10.103-v7l+/include/config/can/mcp251x.h
/usr/src/linux-headers-5.10.103-v7+/include/config/can/mcp251x.h
/usr/src/linux-headers-5.10.103+/include/config/can/mcp251x.h
```
What do I have to change?

**Comment by loxK** [comment]
I cannot compile with kernel 6.1.21-v8+ either:

```
# make
make -C /lib/modules/6.1.24-v8+/build M=/root/mcp251x modules
make[1]: Entering directory '/usr/lib/modules/6.1.24-v8+/build'
make[1]: *** No rule to make target 'modules'.  Stop.
make[1]: Leaving directory '/usr/lib/modules/6.1.24-v8+/build'
make: *** [Makefile:4: all] Error 2
```

```
# ls -lah /usr/lib/modules/6.1.24-v8+/
total 2.6M
drwxr-xr-x  4 root root 4.0K Apr 22 14:26 .
drwxr-xr-x  4 root root 4.0K Apr 22 14:10 ..
drwxr-xr-x  2 root root 4.0K Apr 22 14:26 build
drwxr-xr-x 11 root root 4.0K Apr 22 14:10 kernel
-rw-r--r--  1 root root 604K Apr 22 14:10 modules.alias
-rw-r--r--  1 root root 630K Apr 22 14:10 modules.alias.bin
-rw-r--r--  1 root root  16K Apr 22 14:10 modules.builtin
-rw-r--r--  1 root root    0 Apr 22 14:10 modules.builtin.alias.bin
-rw-r--r--  1 root root  18K Apr 22 14:10 modules.builtin.bin
-rw-r--r--  1 root root  89K Apr 22 14:10 modules.builtin.modinfo
-rw-r--r--  1 root root 227K Apr 22 14:10 modules.dep
-rw-r--r--  1 root root 305K Apr 22 14:10 modules.dep.bin
-rw-r--r--  1 root root  384 Apr 22 14:10 modules.devname
-rw-r--r--  1 root root  68K Apr 22 14:10 modules.order
-rw-r--r--  1 root root  949 Apr 22 14:10 modules.softdep
-rw-r--r--  1 root root 284K Apr 22 14:10 modules.symbols
-rw-r--r--  1 root root 345K Apr 22 14:10 modules.symbols.bin
```

**Comment by mizrex** [comment]
Any luck with the new kernels?
